apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fathom
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - fathom.example.com
    secretName: fathom-tls
  rules:
  - host: fathom.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: fathom
          servicePort: http
