apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fathom-persistent-storage
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi