kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: statping-persistent-storage
spec:
  storageClassName: rook-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
